<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>SchoolboyRunawayTrainer</AssemblyName>
    <RootNamespace>SchoolboyRunawayTrainer</RootNamespace>
    <Version>0.1.0</Version>
    <ApplicationIcon></ApplicationIcon>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>embedded</DebugType>
    <!-- When publishing: dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true /p:SelfContained=true -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Compression.ZipFile" Version="4.3.0" />
  </ItemGroup>

</Project>
